services:
  - type: web
    name: kaanu-userbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
